### GET all notes
GET http://localhost:3001/api/notes

### PUT existing note
PUT http://localhost:3001/api/notes/67a871106e36f3d9b497c6e9
content-type: application/json

{
  "content": "HTML is easy",
  "important": true
}

### DELETE a note
DELETE http://localhost:3001/api/notes/67a871106e36f3d9b497c6e8

### POST request to example server
POST http://localhost:3001/api/notes
content-type: application/json

{
  "important": true
}
